/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import classes.Cargo;
import classes.ProcessoSeletivo;
import database.CargoDao;
import database.ProcessoSeletivoDao;
import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author RaphaelBispoIssa
 */
public class TelaEditarProcessoJd extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEditarProcessoJd.class.getName());
    private TelaProcessoSeletivo telaPai;
    private ProcessoSeletivo processoParaEditar;
    /**
     * Creates new form TelaEditarProcessoJd
     */
    public TelaEditarProcessoJd(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    
    public TelaEditarProcessoJd(java.awt.Frame parent, boolean modal, TelaProcessoSeletivo telaPai, ProcessoSeletivo processo) {
        super((java.awt.Frame) null, modal);
        this.telaPai = telaPai;
        this.processoParaEditar = processo; 
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        carregarCargos();
        preencherCampos();  
    }
    
    
    
    private void carregarCargos() {
        try {   
            CargoDao cargoDao = new CargoDao();
            List<Cargo> cargos = cargoDao.listar();

            jcbCargo.removeAllItems();
            jcbCargo.addItem("Selecione um cargo...");

            for (Cargo cargo : cargos) {
                jcbCargo.addItem(cargo.getNome());
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Erro ao carregar os cargos: " + e.getMessage(),
                "Erro no Banco de Dados",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    private void preencherCampos() {
        if (processoParaEditar != null) {
            jtNome.setText(processoParaEditar.getNomeProcesso());
            jtNome.setForeground(Color.BLACK);

            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            if (processoParaEditar.getDataInicio() != null) {
                jtDataInicio.setText(processoParaEditar.getDataInicio().format(dtf));
            }
            if (processoParaEditar.getDataFim() != null) {
                jtDataFim.setText(processoParaEditar.getDataFim().format(dtf));
            }

            try {
                CargoDao cargoDao = new CargoDao();
                List<Cargo> cargos = cargoDao.listar();
                for (Cargo c : cargos) {
                    if (c.getId() == processoParaEditar.getIdCargo()) {
                        jcbCargo.setSelectedItem(c.getNome());
                        break;
                    }
                }
            } catch (SQLException e) {
                logger.log(java.util.logging.Level.SEVERE, "Erro ao carregar cargo selecionado", e);
            }
        }
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbEditar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jcbCargo = new javax.swing.JComboBox<>();
        jtDataInicio = new javax.swing.JFormattedTextField();
        jtDataFim = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(233, 243, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(29, 45, 68));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 45, 68));
        jLabel1.setText("Editar Processos Seletivo");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 290, 30));

        jtNome.setForeground(new java.awt.Color(153, 153, 153));
        jtNome.setText("Digite o nome do processo...");
        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });
        jPanel2.add(jtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 620, 30));

        jLabel2.setBackground(new java.awt.Color(29, 45, 68));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(29, 45, 68));
        jLabel2.setText("Nome");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(29, 45, 68));
        jLabel3.setText("Cargo");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(29, 45, 68));
        jLabel4.setText("Data Início");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(29, 45, 68));
        jLabel5.setText("Data Fim");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        jbEditar.setBackground(new java.awt.Color(31, 53, 80));
        jbEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbEditar.setForeground(new java.awt.Color(255, 255, 255));
        jbEditar.setText("Editar");
        jbEditar.addActionListener(this::jbEditarActionPerformed);
        jPanel2.add(jbEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 90, 40));

        jbCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbCancelar.setForeground(new java.awt.Color(31, 53, 80));
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(this::jbCancelarActionPerformed);
        jPanel2.add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, 40));

        jcbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um cargo..." }));
        jcbCargo.setToolTipText("");
        jcbCargo.addActionListener(this::jcbCargoActionPerformed);
        jPanel2.add(jcbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 152, 620, 30));

        try {
            jtDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtDataInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtDataInicioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtDataInicioFocusLost(evt);
            }
        });
        jPanel2.add(jtDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 290, 30));

        try {
            jtDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(jtDataFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 290, 30));

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusGained
        if (jtNome.getText().equals("Digite o nome do processo...")) {
            jtNome.setText("");
            jtNome.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jtNomeFocusGained

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        if (jtNome.getText().trim().isEmpty()) {
            jtNome.setText("Digite o nome do processo...");
            jtNome.setForeground(Color.GRAY);

        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        String nome = jtNome.getText().trim();

        if (nome.isEmpty() || nome.equals("Digite o nome do processo...")) {
            JOptionPane.showMessageDialog(this, "Informe o nome do processo seletivo.", "Campo Obrigatório", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nomeCargoSelecionado = (String) jcbCargo.getSelectedItem();
        if (nomeCargoSelecionado == null || nomeCargoSelecionado.equals("Selecione um cargo...")) {
            JOptionPane.showMessageDialog(this, "Selecione um cargo válido.", "Campo Obrigatório", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Cargo cargoSelecionado = null;
        try {
            CargoDao cargoDao = new CargoDao();
            List<Cargo> lista = cargoDao.buscarPorNome(nomeCargoSelecionado);
            if (!lista.isEmpty()) {
                cargoSelecionado = lista.get(0);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar dados do cargo: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (cargoSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Cargo não encontrado no sistema.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataInicio = null;
        LocalDate dataFim = null;

        try {
            dataInicio = LocalDate.parse(jtDataInicio.getText().trim(), dtf);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Data de início inválida. Preencha no formato DD/MM/AAAA.", "Data Inválida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String strDataFim = jtDataFim.getText().replace("/", "").trim();
        if (!strDataFim.isEmpty()) {
            try {
                dataFim = LocalDate.parse(jtDataFim.getText().trim(), dtf);
            } catch (DateTimeParseException e) {
                JOptionPane.showMessageDialog(this, "Data de fim inválida. Preencha no formato DD/MM/AAAA.", "Data Inválida", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        if (dataFim != null && dataFim.isBefore(dataInicio)) {
            JOptionPane.showMessageDialog(this, "A data de fim não pode ser anterior à data de início!", "Data Inválida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean mesmoNome = nome.equals(processoParaEditar.getNomeProcesso());
        boolean mesmoCargo = cargoSelecionado.getId() == processoParaEditar.getIdCargo();
        boolean mesmaDataInicio = dataInicio.equals(processoParaEditar.getDataInicio());
        boolean mesmaDataFim = (dataFim == null && processoParaEditar.getDataFim() == null) ||
                               (dataFim != null && dataFim.equals(processoParaEditar.getDataFim()));

        if (mesmoNome && mesmoCargo && mesmaDataInicio && mesmaDataFim) {
            JOptionPane.showMessageDialog(
                this, 
                "Nenhuma alteração foi realizada. Altere pelo menos um campo para salvar.", 
                "Sem Alterações", 
                JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        try {
            processoParaEditar.setNomeProcesso(nome);
            processoParaEditar.setIdCargo(cargoSelecionado.getId());
            processoParaEditar.setDataInicio(dataInicio);
            processoParaEditar.setDataFim(dataFim);

            ProcessoSeletivoDao dao = new ProcessoSeletivoDao();
            if (dao.atualizar(processoParaEditar)) {
                JOptionPane.showMessageDialog(this, "Processo Seletivo alterado com sucesso!");

                if (this.telaPai != null) {
                    this.telaPai.carregarTabela("");
                }

                this.dispose();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar alterações no banco: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jtDataInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDataInicioFocusGained

    }//GEN-LAST:event_jtDataInicioFocusGained

    private void jtDataInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDataInicioFocusLost

    }//GEN-LAST:event_jtDataInicioFocusLost

    private void jcbCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                TelaEditarProcessoJd dialog = new TelaEditarProcessoJd(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JComboBox<String> jcbCargo;
    private javax.swing.JFormattedTextField jtDataFim;
    private javax.swing.JFormattedTextField jtDataInicio;
    private javax.swing.JTextField jtNome;
    // End of variables declaration//GEN-END:variables
}
