/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author GabrielaCarvalhodeSo
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());
    
    private boolean senhaVisivel = false; //Controla se a senha está oculta ou visivel 
    
    public TelaLogin() {
        initComponents();
        setSize(411, 500); //Define o tamanho da tela 
        setResizable(false); //Impede que a pessoa redimensione a janela
        setLocationRelativeTo(null); //Faz a janela abrir centralizada na tela
        pfCampoSenha.setEchoChar((char) 0); //Mostra "Digite sua senha" sem ser ocultado 
        pfCampoSenha.setText("Digite sua senha"); //Coloca o texto dentro do campo de senha 
        tfCampoEmail.setText("Digite seu e-mail"); //COloca o texto dentro do campo de e-mail
        
        setFocusable(true);
        java.awt.EventQueue.invokeLater(() -> {
        requestFocusInWindow();  //Faz a tela iniciar sem nada selecionado 
        });
    }            
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCorFundo = new javax.swing.JPanel();
        jlLogo = new javax.swing.JLabel();
        tfCampoEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pfCampoSenha = new javax.swing.JPasswordField();
        btOcultarSenha = new javax.swing.JButton();
        btBotaoEntrar = new javax.swing.JButton();
        botaoAjuda = new classes.BotaoAjuda();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpCorFundo.setBackground(new java.awt.Color(233, 243, 255));
        jpCorFundo.setPreferredSize(new java.awt.Dimension(450, 610));

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoLogin.png"))); // NOI18N

        tfCampoEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCampoEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCampoEmailFocusLost(evt);
            }
        });
        tfCampoEmail.addActionListener(this::tfCampoEmailActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("E-mail");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("Senha");

        pfCampoSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfCampoSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfCampoSenhaFocusLost(evt);
            }
        });
        pfCampoSenha.addActionListener(this::pfCampoSenhaActionPerformed);

        btOcultarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/olhoAberto.png"))); // NOI18N
        btOcultarSenha.setBorderPainted(false);
        btOcultarSenha.setContentAreaFilled(false);
        btOcultarSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btOcultarSenha.setFocusPainted(false);
        btOcultarSenha.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btOcultarSenha.setPreferredSize(new java.awt.Dimension(30, 30));
        btOcultarSenha.addActionListener(this::btOcultarSenhaActionPerformed);

        btBotaoEntrar.setBackground(new java.awt.Color(31, 53, 80));
        btBotaoEntrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btBotaoEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btBotaoEntrar.setText("Entrar");
        btBotaoEntrar.setToolTipText("Entrar no MainRH");
        btBotaoEntrar.addActionListener(this::btBotaoEntrarActionPerformed);

        botaoAjuda.setTextoAjuda("Esta é a tela de login do sistema MAINRH, utilizada para autenticação de acesso à plataforma. Para entrar no sistema, preencha o campo **E-mail** com o seu endereço cadastrado e digite sua senha de acesso no campo **Senha**, utilizando o ícone de olho ao lado para exibir ou ocultar os caracteres digitados conforme necessário. Após preencher as credenciais, clique no botão **Entrar** para validar seu acesso e ser redirecionado ao painel principal. Caso não possua um cadastro ativo ou tenha esquecido suas credenciais, entre em contato com o suporte ou com a equipe de administração da sua empresa.");

        javax.swing.GroupLayout jpCorFundoLayout = new javax.swing.GroupLayout(jpCorFundo);
        jpCorFundo.setLayout(jpCorFundoLayout);
        jpCorFundoLayout.setHorizontalGroup(
            jpCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCorFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCorFundoLayout.createSequentialGroup()
                        .addGroup(jpCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pfCampoSenha)
                            .addGroup(jpCorFundoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(211, 211, 211))
                            .addComponent(tfCampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btOcultarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
            .addGroup(jpCorFundoLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(btBotaoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCorFundoLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(jlLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpCorFundoLayout.setVerticalGroup(
            jpCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCorFundoLayout.createSequentialGroup()
                .addGroup(jpCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCorFundoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jlLogo))
                    .addComponent(botaoAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pfCampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOcultarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btBotaoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpCorFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCorFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCampoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCampoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCampoEmailActionPerformed

    private void pfCampoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfCampoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfCampoSenhaActionPerformed

    private void pfCampoSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfCampoSenhaFocusGained
        if (String.valueOf(pfCampoSenha.getPassword()).equals("Digite sua senha")) {
            pfCampoSenha.setText("");
            pfCampoSenha.setEchoChar('•');
        } // cria o evento de placeholder
    }//GEN-LAST:event_pfCampoSenhaFocusGained

    private void pfCampoSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfCampoSenhaFocusLost
        if (pfCampoSenha.getPassword().length == 0) {
            pfCampoSenha.setEchoChar((char) 0);
            pfCampoSenha.setText("Digite sua senha");
        }// cria o evento de placeholder
    }//GEN-LAST:event_pfCampoSenhaFocusLost

    private void tfCampoEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCampoEmailFocusGained
        if (tfCampoEmail.getText().equals("Digite seu e-mail")) {
            tfCampoEmail.setText("");
        } // cria o evento de placeholder
    }//GEN-LAST:event_tfCampoEmailFocusGained

    private void tfCampoEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCampoEmailFocusLost
        if (tfCampoEmail.getText().isEmpty()) {
            tfCampoEmail.setText("Digite seu e-mail");
        }    
    }//GEN-LAST:event_tfCampoEmailFocusLost

    private void btOcultarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOcultarSenhaActionPerformed
        if (senhaVisivel) {
           pfCampoSenha.setEchoChar('•');
           senhaVisivel = false;

           btOcultarSenha.setIcon(new javax.swing.ImageIcon(
              getClass().getResource("/icons/olhoFechado.png")
            ));

        } else {
             pfCampoSenha.setEchoChar((char) 0);
             senhaVisivel = true;

             btOcultarSenha.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/icons/olhoAberto.png")
            ));
        } // Alterna a visibilidade da senha e a imagem do olho
    }//GEN-LAST:event_btOcultarSenhaActionPerformed

    private void btBotaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBotaoEntrarActionPerformed
        
        TelaMenu menu = new TelaMenu();
        menu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btBotaoEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private classes.BotaoAjuda botaoAjuda;
    private javax.swing.JButton btBotaoEntrar;
    private javax.swing.JButton btOcultarSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JPanel jpCorFundo;
    private javax.swing.JPasswordField pfCampoSenha;
    private javax.swing.JTextField tfCampoEmail;
    // End of variables declaration//GEN-END:variables
}
