/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import classes.Usuario;
import database.LoginDao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author GabrielaCarvalhodeSo
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());
    
    private boolean senhaVisivel = false; //Controla se a senha está oculta ou visivel 
    
    public TelaLogin() {
        initComponents();
        classes.Acessibilidade.configurarTela(this);
        setSize(411, 500); //Define o tamanho da tela 
        setResizable(false); //Impede que a pessoa redimensione a janela
        setLocationRelativeTo(null); //Faz a janela abrir centralizada na tela
        pfCampoSenha.setEchoChar((char) 0); //Mostra "Digite sua senha" sem ser ocultado 
        pfCampoSenha.setText("Digite sua senha"); //Coloca o texto dentro do campo de senha 
        tfCampoEmail.setText("Digite seu e-mail"); //COloca o texto dentro do campo de e-mail
        
        
        configurarAcessibilidade();
        java.awt.EventQueue.invokeLater(() -> {
        tfCampoEmail.requestFocusInWindow();  // Força o foco no campo de e-mail
        tfCampoEmail.setCaretPosition(0);
        });
    }            
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCorFundo = new javax.swing.JPanel();
        jlLogo = new javax.swing.JLabel();
        tfCampoEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pfCampoSenha = new javax.swing.JPasswordField();
        btOcultarSenha = new javax.swing.JButton();
        btBotaoEntrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botaoAjuda1 = new classes.BotaoAjuda();
        btAcessibilidade = new classes.BotaoAcessibilidade();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpCorFundo.setBackground(new java.awt.Color(233, 243, 255));
        jpCorFundo.setPreferredSize(new java.awt.Dimension(450, 610));

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoLogin.png"))); // NOI18N

        tfCampoEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCampoEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCampoEmailFocusLost(evt);
            }
        });
        tfCampoEmail.addActionListener(this::tfCampoEmailActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("E-mail");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("Senha");

        pfCampoSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfCampoSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfCampoSenhaFocusLost(evt);
            }
        });
        pfCampoSenha.addActionListener(this::pfCampoSenhaActionPerformed);

        btOcultarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/olhoAberto.png"))); // NOI18N
        btOcultarSenha.setBorderPainted(false);
        btOcultarSenha.setContentAreaFilled(false);
        btOcultarSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btOcultarSenha.setFocusPainted(false);
        btOcultarSenha.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btOcultarSenha.setPreferredSize(new java.awt.Dimension(30, 30));
        btOcultarSenha.addActionListener(this::btOcultarSenhaActionPerformed);

        btBotaoEntrar.setBackground(new java.awt.Color(31, 53, 80));
        btBotaoEntrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btBotaoEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btBotaoEntrar.setText("Entrar");
        btBotaoEntrar.setToolTipText("Entrar no MainRH");
        btBotaoEntrar.addActionListener(this::btBotaoEntrarActionPerformed);

        jPanel1.setBackground(new java.awt.Color(233, 243, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoAjuda1.addActionListener(this::botaoAjuda1ActionPerformed);
        jPanel1.add(botaoAjuda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, -10, 60, 60));

        btAcessibilidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 204, 255), 1, true));
        btAcessibilidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btAcessibilidade.addActionListener(this::btAcessibilidadeActionPerformed);
        jPanel1.add(btAcessibilidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 5, 160, 38));

        javax.swing.GroupLayout jpCorFundoLayout = new javax.swing.GroupLayout(jpCorFundo);
        jpCorFundo.setLayout(jpCorFundoLayout);
        jpCorFundoLayout.setHorizontalGroup(
            jpCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCorFundoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jpCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlLogo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCorFundoLayout.createSequentialGroup()
                            .addGroup(jpCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pfCampoSenha)
                                .addGroup(jpCorFundoLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(211, 211, 211))
                                .addComponent(tfCampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btOcultarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCorFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCorFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btBotaoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        jpCorFundoLayout.setVerticalGroup(
            jpCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCorFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btOcultarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfCampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btBotaoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCorFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCorFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private final java.beans.PropertyChangeListener preferenciaTeclado = e -> aplicarNavegacao();

    private void configurarAcessibilidade() {
        jlLogo.setIcon(new classes.IconeImagem("/images/Logo.png", 337, 110));
        jPanel1.removeAll();
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 8));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 7));
        btAcessibilidade.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        jPanel1.add(btAcessibilidade);
        javax.swing.JPanel separador = new javax.swing.JPanel();
        separador.setBackground(new java.awt.Color(145, 175, 204));
        separador.setPreferredSize(new java.awt.Dimension(1, 28));
        jPanel1.add(separador);
        botaoAjuda1.setPreferredSize(new java.awt.Dimension(36, 34));
        botaoAjuda1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botaoAjuda1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        botaoAjuda1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 27));
        botaoAjuda1.setTextoAjuda("Preencha seu **e-mail** e sua **senha** e clique em **Entrar**. Use **Acessibilidade** para escolher o modo de navegação.");
        jPanel1.add(botaoAjuda1);
        jLabel1.setLabelFor(tfCampoEmail);
        jLabel2.setLabelFor(pfCampoSenha);
        classes.Acessibilidade.adicionarListener(preferenciaTeclado);
        aplicarNavegacao();
    }

    private void aplicarNavegacao() {
        boolean ativo = classes.Acessibilidade.isTecladoAtivo();
        if (ativo) {
            getRootPane().registerKeyboardAction(e -> btBotaoEntrar.doClick(),
                    javax.swing.KeyStroke.getKeyStroke("ENTER"), javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        } else {
            getRootPane().unregisterKeyboardAction(javax.swing.KeyStroke.getKeyStroke("ENTER"));
        }
        btOcultarSenha.setFocusPainted(ativo);
        botaoAjuda1.setFocusPainted(ativo);
    }

    @Override public void dispose() {
        classes.Acessibilidade.removerListener(preferenciaTeclado);
        super.dispose();
    }

    private void tfCampoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCampoEmailActionPerformed
        if (classes.Acessibilidade.isTecladoAtivo()) btBotaoEntrar.doClick();
    }//GEN-LAST:event_tfCampoEmailActionPerformed

    private void pfCampoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfCampoSenhaActionPerformed
        if (classes.Acessibilidade.isTecladoAtivo()) btBotaoEntrar.doClick();
    }//GEN-LAST:event_pfCampoSenhaActionPerformed

    private void pfCampoSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfCampoSenhaFocusGained
        if (String.valueOf(pfCampoSenha.getPassword()).equals("Digite sua senha")) {
            pfCampoSenha.setText("");
            pfCampoSenha.setEchoChar('•');
        } // cria o evento de placeholder
    }//GEN-LAST:event_pfCampoSenhaFocusGained

    private void pfCampoSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfCampoSenhaFocusLost
        if (pfCampoSenha.getPassword().length == 0) {
            pfCampoSenha.setEchoChar((char) 0);
            pfCampoSenha.setText("Digite sua senha");
        }// cria o evento de placeholder
    }//GEN-LAST:event_pfCampoSenhaFocusLost

    private void tfCampoEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCampoEmailFocusGained
        if (tfCampoEmail.getText().equals("Digite seu e-mail")) {
            tfCampoEmail.setText("");
        } // cria o evento de placeholder
    }//GEN-LAST:event_tfCampoEmailFocusGained

    private void tfCampoEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCampoEmailFocusLost
        if (tfCampoEmail.getText().isEmpty()) {
            tfCampoEmail.setText("Digite seu e-mail");
        }    
    }//GEN-LAST:event_tfCampoEmailFocusLost

    private void btOcultarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOcultarSenhaActionPerformed
        if (senhaVisivel) {
           pfCampoSenha.setEchoChar('•');
           senhaVisivel = false;

           btOcultarSenha.setIcon(new javax.swing.ImageIcon(
              getClass().getResource("/icons/olhoFechado.png")
            ));

        } else {
             pfCampoSenha.setEchoChar((char) 0);
             senhaVisivel = true;

             btOcultarSenha.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/icons/olhoAberto.png")
            ));
        } // Alterna a visibilidade da senha e a imagem do olho
    }//GEN-LAST:event_btOcultarSenhaActionPerformed

    private void btBotaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBotaoEntrarActionPerformed
       
    String email = tfCampoEmail.getText().trim();
    String senha = String.valueOf(pfCampoSenha.getPassword());

    // Verifica se os campos foram preenchidos
    if (email.isEmpty()
            || email.equals("Digite seu e-mail")
            || senha.isEmpty()
            || senha.equals("Digite sua senha")) {

        JOptionPane.showMessageDialog(
                this,
                "Preencha o e-mail e a senha.",
                "Campos obrigatórios",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    try {

        LoginDao dao = new LoginDao();

        Usuario usuario = dao.realizarLogin(email, senha);

        if (usuario != null) {

         String funcao = usuario.getFuncao();

        if ("ADM".equals(funcao)) {
    
        JOptionPane.showMessageDialog(
                this,
                "Bem-vindo(a), " + usuario.getNome() + "!",
                "Login realizado",
                JOptionPane.INFORMATION_MESSAGE
        );

        TelaMenu menu = new TelaMenu();
        menu.setVisible(true);

        this.dispose();

         } else {

        JOptionPane.showMessageDialog(
                this,
                "Este usuário não possui permissão para acessar o sistema.",
                "Acesso negado",
                JOptionPane.WARNING_MESSAGE
            );
        }

        } else {
            
            JOptionPane.showMessageDialog(
                    this,
                    "E-mail ou senha inválidos.",
                    "Login inválido",
                    JOptionPane.WARNING_MESSAGE
            );
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Erro ao acessar o banco de dados:\n" + e.getMessage(),
                "Erro no Banco de Dados",
                JOptionPane.ERROR_MESSAGE
        );
    }
        
    }//GEN-LAST:event_btBotaoEntrarActionPerformed

    private void botaoAjuda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAjuda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAjuda1ActionPerformed

    private void btAcessibilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcessibilidadeActionPerformed
        new TelaAcessibilidade(this).setVisible(true);
    }//GEN-LAST:event_btAcessibilidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private classes.BotaoAjuda botaoAjuda1;
    private classes.BotaoAcessibilidade btAcessibilidade;
    private javax.swing.JButton btBotaoEntrar;
    private javax.swing.JButton btOcultarSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JPanel jpCorFundo;
    private javax.swing.JPasswordField pfCampoSenha;
    private javax.swing.JTextField tfCampoEmail;
    // End of variables declaration//GEN-END:variables
}
