/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import java.awt.Color;

/**
 *
 * @author GabrielaCarvalhodeSo
 */ 
public class TelaEditarProcesso extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaEditarProcesso
     */
    public TelaEditarProcesso() {
   initComponents();

    jtNome.setForeground(Color.GRAY);
    jtDataInicio.setForeground(Color.GRAY);

    javax.swing.SwingUtilities.invokeLater(() -> {
    jbCancelar.requestFocusInWindow();
    
    });
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtDataInicio = new javax.swing.JTextField();
        jtDataFim = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbEditar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jcbCargo = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(233, 243, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(29, 45, 68));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 45, 68));
        jLabel1.setText("Editar Processos Seletivo");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 290, 30));

        jtNome.setForeground(new java.awt.Color(153, 153, 153));
        jtNome.setText("Digite o nome do processo...");
        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });
        jPanel2.add(jtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 660, 30));

        jLabel2.setBackground(new java.awt.Color(29, 45, 68));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(29, 45, 68));
        jLabel2.setText("Nome");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(29, 45, 68));
        jLabel3.setText("Cargo");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jtDataInicio.setForeground(new java.awt.Color(153, 153, 153));
        jtDataInicio.setText("dd/mm/aaaa");
        jtDataInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtDataInicioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtDataInicioFocusLost(evt);
            }
        });
        jPanel2.add(jtDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 310, 30));

        jtDataFim.setForeground(new java.awt.Color(153, 153, 153));
        jtDataFim.setText("dd/mm/aaaa");
        jtDataFim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtDataFimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtDataFimFocusLost(evt);
            }
        });
        jPanel2.add(jtDataFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 330, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(29, 45, 68));
        jLabel4.setText("Data Início");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(29, 45, 68));
        jLabel5.setText("Data Fim");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        jbEditar.setBackground(new java.awt.Color(31, 53, 80));
        jbEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbEditar.setForeground(new java.awt.Color(255, 255, 255));
        jbEditar.setText("Editar");
        jPanel2.add(jbEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 90, 40));

        jbCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbCancelar.setForeground(new java.awt.Color(31, 53, 80));
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(this::jbCancelarActionPerformed);
        jPanel2.add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, 40));

        jcbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um cargo..." }));
        jcbCargo.setToolTipText("");
        jPanel2.add(jcbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 152, 660, 30));

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusGained
        if (jtNome.getText().equals("Digite o nome do processo...")) {
            jtNome.setText("");
            jtNome.setForeground(Color.BLACK);
        }   // placeholder do campo nome   
    }//GEN-LAST:event_jtNomeFocusGained

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        if (jtNome.getText().trim().isEmpty()) {
            jtNome.setText("Digite o nome do processo...");
            jtNome.setForeground(Color.GRAY);

        }  //placeholder do campo nome 
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtDataInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDataInicioFocusGained
        if (jtDataInicio.getText().equals("dd/mm/aaaa")) {
            jtDataInicio.setText("");
            jtDataInicio.setForeground(Color.BLACK);
        } // placeholder do campo data inicio                                                          
    }//GEN-LAST:event_jtDataInicioFocusGained

    private void jtDataInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDataInicioFocusLost
        if (jtDataInicio.getText().trim().isEmpty()) {
            jtDataInicio.setText("dd/mm/aaaa");
            jtDataInicio.setForeground(Color.GRAY);
        } //placeholder do campo data inicio       
    }//GEN-LAST:event_jtDataInicioFocusLost

    private void jtDataFimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDataFimFocusGained
        if (jtDataFim.getText().equals("dd/mm/aaaa")) {
            jtDataFim.setText("");
            jtDataFim.setForeground(Color.BLACK);
        } //placeholder do campo data fim 
    }//GEN-LAST:event_jtDataFimFocusGained

    private void jtDataFimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDataFimFocusLost
        if (jtDataFim.getText().trim().isEmpty()) {
            jtDataFim.setText("dd/mm/aaaa");
            jtDataFim.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jtDataFimFocusLost

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
            this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JComboBox<String> jcbCargo;
    private javax.swing.JTextField jtDataFim;
    private javax.swing.JTextField jtDataInicio;
    private javax.swing.JTextField jtNome;
    // End of variables declaration//GEN-END:variables
}
