/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author GabrielaCarvalhodeSo
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        setSize(411, 500); //Define o tamanho da tela 
        setResizable(false); //Impede que a pessoa redimensione a janela
        setLocationRelativeTo(null); //Faz a janela abrir centralizada na tela
        jpCampoSenha.setEchoChar((char) 0); //Mostra "Digite sua senha" sem ser ocultado 
        jpCampoSenha.setText("Digite sua senha"); //Coloca o texto dentro do campo de senha 
        jtCampoEmail.setText("Digite seu e-mail"); //COloca o texto dentro do campo de e-mail
        
        setFocusable(true);
        java.awt.EventQueue.invokeLater(() -> {
        requestFocusInWindow();  //Faz a tela iniciar sem nada selecionado 
        });
    }            
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCorFundo = new javax.swing.JPanel();
        jlLogo = new javax.swing.JLabel();
        jtCampoEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpCampoSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(411, 500));

        jpCorFundo.setBackground(new java.awt.Color(233, 243, 255));
        jpCorFundo.setPreferredSize(new java.awt.Dimension(450, 610));

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LogoLogin.png"))); // NOI18N

        jtCampoEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtCampoEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCampoEmailFocusLost(evt);
            }
        });
        jtCampoEmail.addActionListener(this::jtCampoEmailActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("E-mail");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("Senha");

        jpCampoSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpCampoSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpCampoSenhaFocusLost(evt);
            }
        });
        jpCampoSenha.addActionListener(this::jpCampoSenhaActionPerformed);

        javax.swing.GroupLayout jpCorFundoLayout = new javax.swing.GroupLayout(jpCorFundo);
        jpCorFundo.setLayout(jpCorFundoLayout);
        jpCorFundoLayout.setHorizontalGroup(
            jpCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCorFundoLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jpCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCorFundoLayout.createSequentialGroup()
                        .addGroup(jpCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jtCampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpCampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCorFundoLayout.createSequentialGroup()
                        .addComponent(jlLogo)
                        .addGap(27, 27, 27))))
        );
        jpCorFundoLayout.setVerticalGroup(
            jpCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCorFundoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlLogo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtCampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpCampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCorFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCorFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtCampoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCampoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCampoEmailActionPerformed

    private void jpCampoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpCampoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpCampoSenhaActionPerformed

    private void jpCampoSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpCampoSenhaFocusGained
        if (String.valueOf(jpCampoSenha.getPassword()).equals("Digite sua senha")) {
            jpCampoSenha.setText("");
            jpCampoSenha.setEchoChar('•');
        } // cria o evento de placeholder
    }//GEN-LAST:event_jpCampoSenhaFocusGained

    private void jpCampoSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpCampoSenhaFocusLost
        if (jpCampoSenha.getPassword().length == 0) {
            jpCampoSenha.setEchoChar((char) 0);
            jpCampoSenha.setText("Digite sua senha");
        }// cria o evento de placeholder
    }//GEN-LAST:event_jpCampoSenhaFocusLost

    private void jtCampoEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCampoEmailFocusGained
        if (jtCampoEmail.getText().equals("Digite seu e-mail")) {
            jtCampoEmail.setText("");
        } // cria o evento de placeholder
    }//GEN-LAST:event_jtCampoEmailFocusGained

    private void jtCampoEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCampoEmailFocusLost
        if (jtCampoEmail.getText().isEmpty()) {
            jtCampoEmail.setText("Digite seu e-mail");
        }    
    }//GEN-LAST:event_jtCampoEmailFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JPasswordField jpCampoSenha;
    private javax.swing.JPanel jpCorFundo;
    private javax.swing.JTextField jtCampoEmail;
    // End of variables declaration//GEN-END:variables
}
