/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import telas.processo.TelaProcessoSeletivo;
import telas.gestao.TelaGestaoRec;
import telas.cargo.TelaCargo;
import javax.swing.JInternalFrame;

/**
 *
 * @author RaphaelBispoIssa
 */
public class TelaMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMenu.class.getName());

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
        // Maximiza a janela para ocupar a tela toda ao iniciar
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botaoAjuda1 = new Classes.BotaoAjuda();
        menuBar = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        menuCargo = new javax.swing.JMenuItem();
        menuProcessoSeletivo = new javax.swing.JMenuItem();
        menuRecrutador = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuSair = new javax.swing.JMenuItem();
        menu2 = new javax.swing.JMenu();
        menuCadastro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        painelPrincipal.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(233, 243, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logo.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 70, 0));
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(233, 243, 255));

        botaoAjuda1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botaoAjuda1.setText(" ? ");
        botaoAjuda1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        botaoAjuda1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(botaoAjuda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(botaoAjuda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 606, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);

        painelPrincipal.add(jPanel1, java.awt.BorderLayout.CENTER);

        menu1.setText("Gerenciamento");
        menu1.setToolTipText("Este é o menu!");

        menuCargo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuCargo.setText("Gerenciar Cargos");
        menuCargo.setToolTipText("Aqui você pode criar, editar, listar e excluir cargos!");
        menuCargo.addActionListener(this::menuCargoActionPerformed);
        menu1.add(menuCargo);

        menuProcessoSeletivo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        menuProcessoSeletivo.setText("Abrir Processo Seletivo");
        menuProcessoSeletivo.setToolTipText("Aqui você pode criar, editar, listar e excluir processos seletivos!");
        menuProcessoSeletivo.addActionListener(this::menuProcessoSeletivoActionPerformed);
        menu1.add(menuProcessoSeletivo);

        menuRecrutador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menuRecrutador.setText("Vincular Recrutadores");
        menuRecrutador.setToolTipText("Aqui você pode vincular recrutadores a um processo seletivo!");
        menuRecrutador.addActionListener(this::menuRecrutadorActionPerformed);
        menu1.add(menuRecrutador);
        menu1.add(jSeparator1);

        menuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        menuSair.setText("Sair do Sistema");
        menuSair.setToolTipText("Aqui você sai do sistema, fechando tudo!");
        menuSair.addActionListener(this::menuSairActionPerformed);
        menu1.add(menuSair);

        menuBar.add(menu1);

        menu2.setText("Cadastro");
        menu2.setToolTipText("Menu para cadastro");

        menuCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        menuCadastro.setText("Cadastrar Usuário");
        menuCadastro.setToolTipText("Cadastre administrador ou recrutador por aqui");
        menuCadastro.addActionListener(this::menuCadastroActionPerformed);
        menu2.add(menuCadastro);

        menuBar.add(menu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCargoActionPerformed

    abrirJanelaInterna(new TelaCargo());
    }//GEN-LAST:event_menuCargoActionPerformed

    private void abrirJanelaInterna(JInternalFrame frame) {
        boolean aberta = false;
        
        for (JInternalFrame f : painelPrincipal.getAllFrames()) {
            if (f.getClass().equals(frame.getClass())) {
                aberta = true;
                try {
                    if (f.isIcon()) {
                        f.setIcon(false); // Restaura se estiver minimizada
                    }
                    f.setSelected(true);
                    f.toFront();
                } catch (java.beans.PropertyVetoException e) {
                    e.printStackTrace();
                }
                break;
            }
        }
        
        if (!aberta) {
            painelPrincipal.add(frame);
            frame.setVisible(true);
        }
    }
    
    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        Object[] opcoes = {"Sim", "Não"};

        int opcao = javax.swing.JOptionPane.showOptionDialog(
            this,
            "Tem certeza que deseja sair do sistema?",
            "Atenção",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE,
            null,           // Ícone customizado (null usa o padrão de WARNING)
            opcoes,         // Os textos dos seus botões
            opcoes[1]       // Botão selecionado por padrão ao apertar Enter ("Não")
        );

        if (opcao == 0) {   // 0 é o primeiro botão ("Sim"), 1 é o segundo ("Não")
            System.exit(0);
        }
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerformed
        TelaCadastroUsuarioJd cadastroUsuario = new TelaCadastroUsuarioJd(null,true);
        cadastroUsuario.setVisible(true);
    }//GEN-LAST:event_menuCadastroActionPerformed


    private void menuRecrutadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRecrutadorActionPerformed

        abrirJanelaInterna(new TelaGestaoRec());
    }//GEN-LAST:event_menuRecrutadorActionPerformed

    private void menuProcessoSeletivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcessoSeletivoActionPerformed
        abrirJanelaInterna(new TelaProcessoSeletivo());
    }//GEN-LAST:event_menuProcessoSeletivoActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Classes.BotaoAjuda botaoAjuda1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menu1;
    private javax.swing.JMenu menu2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuCadastro;
    private javax.swing.JMenuItem menuCargo;
    private javax.swing.JMenuItem menuProcessoSeletivo;
    private javax.swing.JMenuItem menuRecrutador;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JDesktopPane painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
