/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import java.awt.Color;


/**
 *
 * @author RaphaelBispoIssa
 */
public class TelaCargo extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCargo
     */
    public TelaCargo() {
        initComponents();
        customizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void customizarTabela() {
    // 1. Fundo do ScrollPane e Borda do Container
    scrollPane.getViewport().setBackground(java.awt.Color.WHITE);
    scrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 235, 240), 1));

    // 2. Estilização e FONTE DAS LINHAS da Tabela
    tbCargo.setBackground(java.awt.Color.WHITE);
    tbCargo.setRowHeight(38);
    tbCargo.setShowGrid(false);
    tbCargo.setShowHorizontalLines(true);
    tbCargo.setGridColor(new java.awt.Color(245, 245, 245));
    
    // ---> ALTERE O TAMANHO DA FONTE DOS DADOS AQUI <---
    tbCargo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));

    // 3. Renderizador e FONTE DO CABEÇALHO
    javax.swing.table.DefaultTableCellRenderer headerRenderer = new javax.swing.table.DefaultTableCellRenderer() {
        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            setBackground(new java.awt.Color(29, 45, 68));
            setForeground(java.awt.Color.WHITE);
            
            // ---> ALTERE O TAMANHO DA FONTE DO CABEÇALHO AQUI <---
            setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            
            setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
            setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            return this;
        }
    };

    for (int i = 0; i < tbCargo.getColumnModel().getColumnCount(); i++) {
        tbCargo.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
    }

    tbCargo.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 35));
}

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDesktopPane = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tfPesquisa = new javax.swing.JTextField();
        tfPesquisa.setText("Digite aqui...");
        tfPesquisa.setForeground(java.awt.Color.GRAY);
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbVoltar = new javax.swing.JLabel();
        botaoAjuda1 = new Classes.BotaoAjuda();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        tbCargo = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btCadastrar = new javax.swing.JButton();

        setTitle("GERENCIAMENTO DE CARGOS");

        painelDesktopPane.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(233, 243, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(233, 243, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(233, 243, 255));

        tfPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPesquisaFocusGained(evt);
            }
        });
        tfPesquisa.addActionListener(this::tfPesquisaActionPerformed);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(29, 45, 68));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 45, 68));
        jLabel1.setText("Cargos");

        lbVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Voltar.png"))); // NOI18N
        lbVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbVoltarMouseClicked(evt);
            }
        });

        botaoAjuda1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botaoAjuda1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(890, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoAjuda1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoAjuda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(233, 243, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 32, 20, 32));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 32));

        jLabel3.setBackground(new java.awt.Color(29, 45, 68));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(29, 45, 68));
        jLabel3.setText("Cargos cadastrados");

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrollPane.setForeground(new java.awt.Color(255, 255, 255));

        tbCargo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbCargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"DEV SENIOR"},
                {"DEV PLENO"},
                {"DEV JUNIOR"},
                {"DEVEDOR DO SERASA"},
                {"sdvsv"},
                {"sdvsvsvsdv"},
                {"sdvsdvsv"},
                {"sdvsvsv"},
                {"sdvsvsdv"},
                {"sdvsvsv"},
                {"sdvsvsv"},
                {"svsvsvsvsvvsvdsvsv"},
                {"svsvsvsvsvsdvsvsvsvsvs"},
                {"svsvssv"},
                {"sdvsvsvsvsssssssssssssssssssssss"},
                {"svsvsvsv"},
                {"svsvsvsvs"},
                {"sdvsvsvsvs"},
                {"svsvsvsvsv"},
                {"svsvsvsvsvs"},
                {"svsvsv"},
                {"svsvsvsdvs"},
                {"svsdvsvsvsv"},
                {null}
            },
            new String [] {
                "Cargos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCargo.setToolTipText("Aqui aparecem os cargos já cadastrados em sistema");
        tbCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCargoMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(tbCargo);

        btExcluir.setBackground(new java.awt.Color(192, 1, 1));
        btExcluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir.setText("Excluir");
        btExcluir.setToolTipText("Selecione um cargo da tabela e clique aqui caso deseje excluir o cargo");
        btExcluir.addActionListener(this::btExcluirActionPerformed);

        btEditar.setBackground(new java.awt.Color(11, 176, 142));
        btEditar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btEditar.setForeground(new java.awt.Color(255, 255, 255));
        btEditar.setText("Editar");
        btEditar.setToolTipText("Selecione um cargo da tabela e clique aqui caso deseje editar o cargo");
        btEditar.addActionListener(this::btEditarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1248, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(233, 243, 255));

        btCadastrar.setBackground(new java.awt.Color(31, 53, 80));
        btCadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btCadastrar.setText("Cadastrar");
        btCadastrar.setToolTipText("Clique aqui para cadastrar um novo cargo");
        btCadastrar.addActionListener(this::btCadastrarActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(1206, Short.MAX_VALUE)
                .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        painelDesktopPane.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(painelDesktopPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // Obtém o JDesktopPane no qual a TelaCargo está inserida
        javax.swing.JDesktopPane desktop = getDesktopPane();

        if (desktop != null) {
            TelaCadastro telaCadastro = new TelaCadastro();
            desktop.add(telaCadastro);
            telaCadastro.setVisible(true);
            try {
                telaCadastro.setSelected(true);
                telaCadastro.toFront();
            } catch (java.beans.PropertyVetoException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btCadastrarActionPerformed
                       
    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed

    }//GEN-LAST:event_btExcluirActionPerformed

    private void lbVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_lbVoltarMouseClicked

    private void tfPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesquisaActionPerformed


    private void tfPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPesquisaFocusGained

    }//GEN-LAST:event_tfPesquisaFocusGained

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
    TelaEditarCargo telaEditar = new TelaEditarCargo();
    painelDesktopPane.add(telaEditar);
    telaEditar.setVisible(true);
    try {
        telaEditar.setSelected(true);
        telaEditar.toFront();
    } catch (java.beans.PropertyVetoException e) {
        e.printStackTrace();
    }  
    }//GEN-LAST:event_btEditarActionPerformed
    

    private void tbCargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCargoMouseClicked
        // Verifica se foi um duplo clique com o botão esquerdo do mouse
    if (evt.getClickCount() == 2 && evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
        
        int linhaSelecionada = tbCargo.getSelectedRow();
        
        // Garante que uma linha válida foi clicada
        if (linhaSelecionada != -1) {
            
            // Exemplo: Pegando um valor da primeira coluna (índice 0)
            Object id = tbCargo.getValueAt(linhaSelecionada, 0);
            
        TelaDetalhesCargo telaDetalhe = new TelaDetalhesCargo();
        painelDesktopPane.add(telaDetalhe);
        telaDetalhe.setVisible(true);
        try {
           telaDetalhe.setSelected(true);
            telaDetalhe.toFront();
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }  
            }
      }
    }//GEN-LAST:event_tbCargoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Classes.BotaoAjuda botaoAjuda1;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbVoltar;
    private javax.swing.JDesktopPane painelDesktopPane;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tbCargo;
    private javax.swing.JTextField tfPesquisa;
    // End of variables declaration//GEN-END:variables
}
