/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

/**
 *
 * @author GabrielaCarvalhodeSo
 */
public class TelaProcessoSeletivo extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaProcessoSeletivo
     */
    public TelaProcessoSeletivo() {
        initComponents();
        
        customizarTabela();
        //cor no cabeçalho da tabela 
    }
    
     private void customizarTabela() {
    // 1. Fundo do ScrollPane e Borda do Container
    jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
    jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 235, 240), 1));

    // 2. Estilização e FONTE DAS LINHAS da Tabela
    jtProcessosSeletivos.setBackground(java.awt.Color.WHITE);
    jtProcessosSeletivos.setRowHeight(38);
    jtProcessosSeletivos.setShowGrid(true);
    jtProcessosSeletivos.setShowHorizontalLines(true);
    jtProcessosSeletivos.setGridColor(new java.awt.Color(150, 150, 150));
    
    // ---> ALTERE O TAMANHO DA FONTE DOS DADOS AQUI <---
    jtProcessosSeletivos.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));

    // 3. Renderizador e FONTE DO CABEÇALHO
    javax.swing.table.DefaultTableCellRenderer headerRenderer = new javax.swing.table.DefaultTableCellRenderer() {
        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            setBackground(new java.awt.Color(29, 45, 68));
            setForeground(java.awt.Color.WHITE);
            
            // ---> ALTERE O TAMANHO DA FONTE DO CABEÇALHO AQUI <---
            setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            
            setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
            setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            return this;
        }
    };

    for (int i = 0; i < jtProcessosSeletivos.getColumnModel().getColumnCount(); i++) {
        jtProcessosSeletivos.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
    }

    jtProcessosSeletivos.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 35));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCorFundo = new javax.swing.JPanel();
        jpComponentes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfBarraPesquisa = new javax.swing.JTextField();
        jpListaProcessos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProcessosSeletivos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jpCorFundo.setBackground(new java.awt.Color(233, 243, 255));
        jpCorFundo.setLayout(new java.awt.BorderLayout());

        jpComponentes.setOpaque(false);
        jpComponentes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 53, 80));
        jLabel1.setText("Processos Seletivos");
        jpComponentes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jtfBarraPesquisa.addActionListener(this::jtfBarraPesquisaActionPerformed);
        jpComponentes.add(jtfBarraPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 300, 30));

        jpListaProcessos.setBackground(new java.awt.Color(255, 255, 255));

        jtProcessosSeletivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Processos", "Data de ínicio", "Data de fim"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtProcessosSeletivos.setShowGrid(true);
        jScrollPane1.setViewportView(jtProcessosSeletivos);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(31, 53, 80));
        jLabel2.setText("Lista de processos seletivos");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jpListaProcessosLayout = new javax.swing.GroupLayout(jpListaProcessos);
        jpListaProcessos.setLayout(jpListaProcessosLayout);
        jpListaProcessosLayout.setHorizontalGroup(
            jpListaProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListaProcessosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpListaProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jpListaProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jpListaProcessosLayout.setVerticalGroup(
            jpListaProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListaProcessosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jpComponentes.add(jpListaProcessos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 930, 440));

        jButton2.setText("jButton2");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jpComponentes.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 580, -1, -1));

        jpCorFundo.add(jpComponentes, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCorFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCorFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfBarraPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBarraPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBarraPesquisaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpComponentes;
    private javax.swing.JPanel jpCorFundo;
    private javax.swing.JPanel jpListaProcessos;
    private javax.swing.JTable jtProcessosSeletivos;
    private javax.swing.JTextField jtfBarraPesquisa;
    // End of variables declaration//GEN-END:variables
}
