/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

/**
 *
 * @author gabiru
 */
public class Tela_Cadastro extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tela_Cadastro
     */
    public Tela_Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCorFundo = new javax.swing.JPanel();
        jpComponentes = new javax.swing.JPanel();
        jtfCampoNome = new javax.swing.JTextField();
        jtfCampoDataNascimento = new javax.swing.JTextField();
        jtfCampoCPF = new javax.swing.JTextField();
        jpfCampoSenha = new javax.swing.JPasswordField();
        jtfCampoEmail = new javax.swing.JTextField();
        jpfCampoConfirmarSenha = new javax.swing.JPasswordField();
        jtfCampoTelefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jcbCampoFuncao = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(707, 710));

        jpCorFundo.setBackground(new java.awt.Color(233, 243, 255));
        jpCorFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpComponentes.setOpaque(false);
        jpComponentes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfCampoNome.addActionListener(this::jtfCampoNomeActionPerformed);
        jpComponentes.add(jtfCampoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 280, 44));
        jpComponentes.add(jtfCampoDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 280, 44));
        jpComponentes.add(jtfCampoCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 280, 44));
        jpComponentes.add(jpfCampoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 280, 44));
        jpComponentes.add(jtfCampoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 280, 44));
        jpComponentes.add(jpfCampoConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 280, 44));
        jpComponentes.add(jtfCampoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 280, 44));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("Nome");
        jpComponentes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("Data de Nascimento");
        jpComponentes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("CPF");
        jpComponentes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("E-mail");
        jpComponentes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setText("Senha");
        jpComponentes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setText("Confirmar Senha");
        jpComponentes.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setText("Telefone");
        jpComponentes.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setText("Função");
        jpComponentes.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));

        jButton1.setBackground(new java.awt.Color(31, 53, 80));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jpComponentes.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 580, 40));

        jcbCampoFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma função", "Administrador (a)", "Recrutador (a)" }));
        jpComponentes.add(jcbCampoFuncao, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 280, 44));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(101, 101, 101));
        jLabel2.setText("Preencha os dados abaixo para criar uma conta");
        jpComponentes.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Criar Conta");
        jpComponentes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LogoMenor.png"))); // NOI18N
        jpComponentes.add(jlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jpCorFundo.add(jpComponentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCorFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCorFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCampoNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jcbCampoFuncao;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JPanel jpComponentes;
    private javax.swing.JPanel jpCorFundo;
    private javax.swing.JPasswordField jpfCampoConfirmarSenha;
    private javax.swing.JPasswordField jpfCampoSenha;
    private javax.swing.JTextField jtfCampoCPF;
    private javax.swing.JTextField jtfCampoDataNascimento;
    private javax.swing.JTextField jtfCampoEmail;
    private javax.swing.JTextField jtfCampoNome;
    private javax.swing.JTextField jtfCampoTelefone;
    // End of variables declaration//GEN-END:variables
}
