/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;

/**
 *
 * @author rapha
 */
public class TelaCadastroUsuarioJd extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroUsuarioJd.class.getName());

    /**
     * Creates new form TelaCadastroUsuarioJd
     */
    public TelaCadastroUsuarioJd(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setUndecorated(false);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpComponentes = new javax.swing.JPanel();
        lbVoltar = new javax.swing.JLabel();
        jtfCampoNome = new javax.swing.JTextField();
        jtfCampoDataNascimento = new javax.swing.JTextField();
        jtfCampoCPF = new javax.swing.JTextField();
        jtfCampoEmail = new javax.swing.JTextField();
        jtfCampoTelefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jcbCampoFuncao = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();
        jpCampoSenha = new javax.swing.JPanel();
        jbOlhoSenha = new javax.swing.JButton();
        jpfCampoSenha = new javax.swing.JPasswordField();
        jpCampoConfirmarSenha = new javax.swing.JPanel();
        jbOlhoConfirmarSenha = new javax.swing.JButton();
        jpfCampoConfirmarSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(233, 243, 255));

        jpComponentes.setBackground(new java.awt.Color(233, 243, 255));
        jpComponentes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpComponentes.setMaximumSize(new java.awt.Dimension(620, 660));
        jpComponentes.setMinimumSize(new java.awt.Dimension(620, 660));
        jpComponentes.setOpaque(false);
        jpComponentes.setPreferredSize(new java.awt.Dimension(620, 660));
        jpComponentes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbVoltar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Voltar.png"))); // NOI18N
        lbVoltar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lbVoltar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jpComponentes.add(lbVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jtfCampoNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfCampoNome.setForeground(new java.awt.Color(153, 153, 153));
        jtfCampoNome.setText("Digite o nome");
        jpComponentes.add(jtfCampoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 280, 44));

        jtfCampoDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfCampoDataNascimento.setForeground(new java.awt.Color(153, 153, 153));
        jtfCampoDataNascimento.setText("dd/mm/aaaa");
        jpComponentes.add(jtfCampoDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 280, 44));

        jtfCampoCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfCampoCPF.setForeground(new java.awt.Color(153, 153, 153));
        jtfCampoCPF.setText("000.000.000-00");
        jpComponentes.add(jtfCampoCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 280, 44));

        jtfCampoEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfCampoEmail.setForeground(new java.awt.Color(153, 153, 153));
        jtfCampoEmail.setText("Digite o e-mail");
        jpComponentes.add(jtfCampoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 280, 44));

        jtfCampoTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfCampoTelefone.setForeground(new java.awt.Color(153, 153, 153));
        jtfCampoTelefone.setText("Digite o telefone");
        jpComponentes.add(jtfCampoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 280, 44));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("Nome");
        jpComponentes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("Data de Nascimento");
        jpComponentes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("CPF");
        jpComponentes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("E-mail");
        jpComponentes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setText("Senha");
        jpComponentes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setText("Confirmar Senha");
        jpComponentes.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setText("Telefone");
        jpComponentes.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setText("Função");
        jpComponentes.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        jButton1.setBackground(new java.awt.Color(31, 53, 80));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cadastrar");
        jpComponentes.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 580, 40));

        jcbCampoFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma função", "Administrador (a)", "Recrutador (a)" }));
        jpComponentes.add(jcbCampoFuncao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 280, 44));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(101, 101, 101));
        jLabel2.setText("Preencha os dados abaixo para criar uma conta");
        jpComponentes.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Criar Conta");
        jpComponentes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LogoMenor.png"))); // NOI18N
        jpComponentes.add(jlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jpCampoSenha.setOpaque(false);
        jpCampoSenha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbOlhoSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/olhoAberto.png"))); // NOI18N
        jbOlhoSenha.setBorderPainted(false);
        jbOlhoSenha.setContentAreaFilled(false);
        jbOlhoSenha.setFocusPainted(false);
        jbOlhoSenha.setFocusable(false);
        jpCampoSenha.add(jbOlhoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 6, 32, 32));

        jpfCampoSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jpfCampoSenha.setForeground(new java.awt.Color(153, 153, 153));
        jpfCampoSenha.setText("Digite a senha");
        jpCampoSenha.add(jpfCampoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 44));

        jpComponentes.add(jpCampoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 280, 44));

        jpCampoConfirmarSenha.setOpaque(false);
        jpCampoConfirmarSenha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbOlhoConfirmarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/olhoAberto.png"))); // NOI18N
        jbOlhoConfirmarSenha.setBorderPainted(false);
        jbOlhoConfirmarSenha.setContentAreaFilled(false);
        jbOlhoConfirmarSenha.setFocusPainted(false);
        jbOlhoConfirmarSenha.setFocusable(false);
        jpCampoConfirmarSenha.add(jbOlhoConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 6, 32, 32));

        jpfCampoConfirmarSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jpfCampoConfirmarSenha.setForeground(new java.awt.Color(153, 153, 153));
        jpfCampoConfirmarSenha.setText("Confirme a senha");
        jpCampoConfirmarSenha.add(jpfCampoConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 44));

        jpComponentes.add(jpCampoConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 280, 44));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                TelaCadastroUsuarioJd dialog = new TelaCadastroUsuarioJd(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbOlhoConfirmarSenha;
    private javax.swing.JButton jbOlhoSenha;
    private javax.swing.JComboBox<String> jcbCampoFuncao;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JPanel jpCampoConfirmarSenha;
    private javax.swing.JPanel jpCampoSenha;
    private javax.swing.JPanel jpComponentes;
    private javax.swing.JPasswordField jpfCampoConfirmarSenha;
    private javax.swing.JPasswordField jpfCampoSenha;
    private javax.swing.JTextField jtfCampoCPF;
    private javax.swing.JTextField jtfCampoDataNascimento;
    private javax.swing.JTextField jtfCampoEmail;
    private javax.swing.JTextField jtfCampoNome;
    private javax.swing.JTextField jtfCampoTelefone;
    private javax.swing.JLabel lbVoltar;
    // End of variables declaration//GEN-END:variables
}
